name: iOS starter workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Config.swift
        run: |
          cat <<EOF > KinoPub/Shared/PrivateKeys.swift
          import Foundation

          extension Config {
              struct GoogleCloudKeys {
                  let gcmMessageIDKey = ""
              }

              static let firebase = GoogleCloudKeys()

              struct IMBDKeys {
                  let key = ""
                  let backdropBase = ""
              }

              static let themoviedb = IMBDKeys()

              struct KinoPubKeys {
                  let clientId = "xbmc"
                  let clientSecret = "${{ secrets.KINOPUB_CLIENT_SECRET }}"
                  let domain = "https://kino.pub"
                  let base = "https://api.service-kp.com/"
              }

              static let kinopub = KinoPubKeys()
          }
          EOF

      - name: Build
        env:
          platform: ${{ 'iOS Simulator' }}
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          set -o pipefail && xcodebuild build -scheme "KinoPub" -destination "platform=$platform,name=$device" | xcbeautify --renderer github-actions
