name: Build app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build application
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Config.swift
        run: |
          cat <<EOF > KinoPub/Shared/PrivateKeys.swift
          import Foundation

          extension Config {
              struct GoogleCloudKeys {
                  let gcmMessageIDKey = ""
              }

              static let firebase = GoogleCloudKeys()

              struct IMBDKeys {
                  let key = ""
                  let backdropBase = ""
              }

              static let themoviedb = IMBDKeys()

              struct KinoPubKeys {
                  let clientId = "xbmc"
                  let clientSecret = "${{ secrets.KINOPUB_CLIENT_SECRET }}"
                  let domain = "https://kino.pub"
                  let base = "https://api.service-kp.com/"
              }

              static let kinopub = KinoPubKeys()
          }
          EOF

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable
      - name: Build
        env:
          platform: ${{ 'iOS' }}
        run: |
          set -o pipefail && xcodebuild build -workspace KinoPub.xcworkspace -scheme KinoPub \
            -destination "generic/platform=$platform" CODE_SIGNING_ALLOWED=NO \
           | xcbeautify --renderer github-actions
